### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by kaprat** [snollidea/peppy-calendarview#2]
![capture](https://user-images.githubusercontent.com/29137068/42013351-74d88bda-7aba-11e8-9781-b231d03fa5ff.PNG)

**Comment by williamkibira** [comment]
Any chance any one has figured out how to get this library or what repository it might be on ? 
I am facing the same issue , and this library is too awesome to pass over .

**Comment by snollidea** [comment]
Sorry, but I will not support this library and do not recommend adding it to your project. 
You can add it as module.
